/* See LICENSE in the root of this project for change info */
#ifndef MONSYM_H
#define MONSYM_H

/*
 * Monster classes.  Below, are the corresponding default characters for
 * them.  Monster class 0 is not used or defined so we can use it as a
 * NULL character.
 */
enum {
    S_ANT = 1,
    S_BLOB,
    S_COCKATRICE,
    S_DOG,
    S_EYE,
    S_FELINE,
    S_GREMLIN,
    S_HUMANOID,
    S_IMP,
    S_JELLY,
    S_KOBOLD,
    S_LEPRECHAUN,
    S_MIMIC,
    S_NYMPH,
    S_ORC,
    S_PIERCER,
    S_QUADRUPED,
    S_RODENT,
    S_SPIDER,
    S_TRAPPER,
    S_UNICORN,
    S_VORTEX,
    S_WORM,
    S_XAN,
    S_LIGHT,
    S_ZRUTY,
    S_ANGEL,
    S_BAT,
    S_CENTAUR,
    S_DRAGON,
    S_ELEMENTAL,
    S_FUNGUS,
    S_GNOME,
    S_GIANT,

    S_JABBERWOCK = 36,
    S_KOP,
    S_LICH,
    S_MUMMY,
    S_NAGA,
    S_OGRE,
    S_PUDDING,
    S_QUANTMECH,
    S_RUSTMONST,
    S_SNAKE,
    S_TROLL,
    S_UMBER,
    S_VAMPIRE,
    S_WRAITH,
    S_XORN,
    S_YETI,
    S_ZOMBIE,
    S_HUMAN,
    S_GHOST,
    S_GOLEM,
    S_DEMON,
    S_EEL,
    S_LIZARD,

    S_WORM_TAIL,
    S_MIMIC_DEF,

    MAXMCLASSES, /* number of monster classes */
};

/*
 * Default characters for monsters.  These correspond to the monster classes
 * above.
 */
enum {
    DEF_ANT = 'a',
    DEF_BLOB,
    DEF_COCKATRICE,
    DEF_DOG,
    DEF_EYE,
    DEF_FELINE,
    DEF_GREMLIN,
    DEF_HUMANOID,
    DEF_IMP,
    DEF_JELLY,
    DEF_KOBOLD,
    DEF_LEPRECHAUN,
    DEF_MIMIC,
    DEF_NYMPH,
    DEF_ORC,
    DEF_PIERCER,
    DEF_QUADRUPED,
    DEF_RODENT,
    DEF_SPIDER,
    DEF_TRAPPER,
    DEF_UNICORN,
    DEF_VORTEX,
    DEF_WORM,
    DEF_XAN,
    DEF_LIGHT,
    DEF_ZRUTY,

    DEF_ANGEL = 'A',
    DEF_BAT,
    DEF_CENTAUR,
    DEF_DRAGON,
    DEF_ELEMENTAL,
    DEF_FUNGUS,
    DEF_GNOME,
    DEF_GIANT,
    DEF_INVISIBLE,
    DEF_JABBERWOCK,
    DEF_KOP,
    DEF_LICH,
    DEF_MUMMY,
    DEF_NAGA,
    DEF_OGRE,
    DEF_PUDDING,
    DEF_QUANTMECH,
    DEF_RUSTMONST,
    DEF_SNAKE,
    DEF_TROLL,
    DEF_UMBER,
    DEF_VAMPIRE,
    DEF_WRAITH,
    DEF_XORN,
    DEF_YETI,
    DEF_ZOMBIE,
    DEF_HUMAN = '@',
    DEF_GHOST = ' ',
    DEF_GOLEM = '\'',
    DEF_DEMON = '&',
    DEF_EEL = ';',
    DEF_LIZARD = ':',

    DEF_WORM_TAIL = '~',
    DEF_MIMIC_DEF = ']',
};

#endif /* MONSYM_H */
